# Generated by Django 3.0.8 on 2020-07-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='activityperiod',
            old_name='member',
            new_name='User',
        ),
    ]
